version: "3.9"


services:
  postgres:
    image: postgres:15.2-alpine
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=bookStore
    ports:
      - 5433:5433


  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on: 
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5433
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 12345
      DATABASE_NAME: bookStore
    command: ["/app/main"]

