version: "3.9"


services:
  database:
    image: postgres:15.2-alpine
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=bookStore
    ports:
      - 5433:5433


  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on: 
      - database
    command: ["/app/main"]

